diff a/drivers/net/wireless/rockchip_wlan/Makefile b/drivers/net/wireless/rockchip_wlan/Makefile	(rejected hunks)
@@ -2,3 +2,5 @@
 obj-$(CONFIG_BCMDHD)	+= rkwifi/
 obj-$(CONFIG_CYW_BCMDHD)	+= cywdhd/
 obj-$(CONFIG_INFINEON_DHD)	+= infineon/
+
+obj-$(CONFIG_RTL8852BE)		+= rtl8852be/
\ No newline at end of file
