diff a/drivers/net/wireless/rockchip_wlan/Makefile b/drivers/net/wireless/rockchip_wlan/Makefile	(rejected hunks)
@@ -3,4 +3,5 @@ obj-$(CONFIG_BCMDHD)	+= rkwifi/
 obj-$(CONFIG_CYW_BCMDHD)	+= cywdhd/
 obj-$(CONFIG_INFINEON_DHD)	+= infineon/
 
-obj-$(CONFIG_RTL8852BE)		+= rtl8852be/
\ No newline at end of file
+obj-$(CONFIG_RTL8852BE)		+= rtl8852be/
+obj-$(CONFIG_RTL8852BU)		+= rtl8852bu/
\ No newline at end of file
